#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Ryuji Hirano
# SPDX-License-Identifier: BSD-3-Clause

import sys
import datetime

dt = datetime.datetime.now()

st = 0

st = (dt.month) + (dt.day) + (dt.hour) + (dt.minute)

st2 = bin(st)

ist = input("{}は2進数で?".format(st))

if ist == (st2[2:]):
    print("正解")
else:
    print("不正解　正解は{}でした".format((st2)[2:]))
