#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Ryuji Hirano
# SPDX-License-Identifier: BSD-3-Clause

import sys
import datetime

dt = datetime.datetime.now()

st = 0

st = (dt.month) + (dt.day) + (dt.hour) + (dt.minute)

print(st)

